demo/urls.py
from unicodedata import name
from django.urls import URLPattern, path
from . import views
urlpatterns =[
    path('',views.home,name='home'),
    path('table',views.table,name='table'),
    path('create',views.createe,name='create'),
    path('update_order/<int:pk>', views.updateOrder, name='updateOrder'),
    path('delete_order/<int:pk>/', views.deleteOrder, name="delete_order"),
    path('leave/<int:pk>',views.leave,name='leave'),
    

]
app_name ='demo'

h/urls.py
from django.contrib import admin
from django.urls import path,include
from . import index
from demo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('demo.urls')),
 
    
]

demo/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class emp(models.Model):
    my_field = models.BooleanField(default=True)
    blog_views=models.IntegerField(default=0)
    name = models.CharField(max_length=100,null=True,blank=True)
    DOB= models.CharField(null=True,blank=True,max_length=100)
    DOJ= models.CharField(null=True,blank=True,max_length=100)
    Department= models.CharField(max_length=100,null=True,blank=True)
    post= models.CharField(max_length=100,null=True,blank=True)
    Adress= models.CharField(max_length=100,null=True,blank=True)
    City=models.CharField(max_length=100,null=True,blank=True)
    Country=models.CharField(max_length=100,null=True,blank=True)
   

demo/forms.py
from django.forms import ModelForm
from .models import emp


class empform(ModelForm):
	class Meta:
		model = emp
		fields = '__all__'

demo/views.py
from email.headerregistry import Address
from multiprocessing import context
#fr om multiprocessing import context
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
#from scrapy import Item
from .models import emp
from .forms import empform

# Create your views here.
def  home(request):
    k= emp.objects.all()
    c=k.count()
    context={'c':c,}
    return render(request,'demo/base.html',context)
def table(request):
    k= emp.objects.all()
    k=k.values()
    #print(k)
       
    context={'k':k,}
    return render(request,'demo/table.html',context) 
def createe(request):
    
    if request.method =='POST' :
        
        print(request.POST)
        print('name',request.POST.get('name')) 
        print('DOB',request.POST.get('DOB'))
        print('DOJ',request.POST.get('DOJ'))
        print('Department',request.POST.get('Department'))
        print('post',request.POST.get('post'))
        print('Adress',request.POST.get('Adress'))
        print('City',request.POST.get('City'))
        print('Country',request.POST.get('Country'))
        e = emp.objects.create(name = request.POST.get('name'), DOB = request.POST.get('DOB'),DOJ = request.POST.get('DOJ'),Department = request.POST.get('Department'),
        post=request.POST.get('post'),Adress=request.POST.get('Adress'),City=request.POST.get('City'),Country=request.POST.get('Country'))
        return redirect('/')
    return render(request,'demo/create.html')    
    
def updateOrder(request, pk):

	order = emp.objects.get(id=pk)
	form = empform(instance=order)

	if request.method == 'POST':
		form = empform(request.POST, instance=order)
		if form.is_valid():
			form.save()
			return redirect('/table')

	context = {'form':form}
	return render(request, 'demo/up.html', context)    
def deleteOrder(request, pk):
	order =emp.objects.get(id=pk)
    
	if request.method == "POST":
		order.delete()
		return redirect('/table')
    
	context = {'item':order}
	return render(request, 'demo/delete.html', context)
def leave(request,pk):
    blog_object=emp.objects.get(id=pk)
    if blog_object.my_field:
        blog_object.my_field = False
    else:
        blog_object.my_field = True
        blog_object. blog_views +=1
       
    blog_object.save()
    return redirect('/table') 

demo/templates/demo/base.html
{% load static%} <!photo insert karne k lea jinja file>
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet"  href="{%  static  'css/ba.css'  %}">
        
        <title>Document</title>
    </head>

    <body>
       
        <div class="ok">
            <img src="{% static 'C:\enviroment\h\demo\image\logo.svg' %}">
            <a href="{% url 'demo:create' %}">
                <h4 id="hey">Create</h4>
            </a>
            <a href="{% url 'demo:table' %}">
                <h4 id="h">Employe List</h4>
            </a>
        </div>
        <div style="height:100px; ">
        <h3>Total number of employee: {{c}}</h3>
    </div >
        <div id="l" style="background-color:rgb(114, 122, 153); height:100px; width:1550px; margin-top:450px; "></div>
        


       
      
        
    </body>

    </html>

demo/templates/demo/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{%  static  'css/ce.css'  %}">
    <title>Register</title>
</head>
<body>
    
    <div style="background-color: rgb(127, 172, 255);"> <img src="{% static 'C:\enviroment\h\demo\image\logo.svg' %}"></div>
    <div id="edit">
    
        <form method="post">
            {% csrf_token %}
           
            <input style="margin-bottom: 20px; margin-left:200px;margin-top: 100px; " type="text" name="name" placeholder="Name" style="margin-right: 200px;margin: bottom 70px;"/>
            <input style="margin-bottom: 20px;" type="text" name="DOB"  placeholder="DOB" onfocus="(this.type='date')" style="margin-right: 200px;" /><br>
            <input style="margin-bottom: 20px;margin-left:200px;"  type="text" name="DOJ" onfocus="(this.type='date')" placeholder="DOJ" style="margin-right: 200px;"/>
            <input style="margin-bottom: 20px;" type="text" name="Department" placeholder="Department" style="margin-right: 200px;"/><br>
            <input style="margin-bottom: 20px;margin-left:200px;" type="text" name="post" placeholder="Post" style="margin-right: 200px;"/>
            <input style="margin-bottom: 20px;" type="text" name="Adress" placeholder="Adress" style="margin-right: 200px;"/><br>
            <input style="margin-bottom: 20px;margin-left:200px;"type="text" name="City" placeholder="City" style="margin-right: 200px;"/>
            <input style="margin-bottom: 20px;"type="text" name="Country" placeholder="Country" style="margin-right: 200px;"/><br>
            <input style=" margin-bottom: 100px;margin-left:340px;" type="submit" value="Submit" />
        </form>
    
    </div>
</body>
</html>

demo/templates/demo/delete.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet"  href="{%  static  'css/new.css'  %}">
	<title>Document</title>
</head>
<body>
	<div style="background-color: rgb(127, 172, 255);"> <img src="{% static 'C:\enviroment\h\demo\image\logo.svg' %}"></div>
	
		<div id="h" style="background-color:rgb(249, 229, 222); height:100px;width:300px; margin-left:450px; margin-right: 300px; ">
			<div class="card" >
				<form method="post" style=" height: 200px ; width:300px; margin-left:450px; margin-top : 100px; margin-left:45px; ">
				<p>Are you sure you want to delete this?</p>
					{% csrf_token %}
					<a class="btn btn-warning" href="{% url 'demo:table' %}">Cancel</a>
	
					<input class="btn btn-danger" type="submit" href="{% url 'demo:table' %}" name="Confirm">
				</form>
			</div>
		</div>
	
</body>
</html>

demo/templates/demo/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>hey anu</h1>
</body>
</html>

demo/templates/demo/ll.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<title>Document</title>
</head>
<body>
	<div style="background-color: rgb(127, 172, 255);"> <img src="{% static 'C:\enviroment\h\demo\image\logo.svg' %}"></div>
	<div class="row">
		<div class="col-md-6">
			<div class="card card-body">
				<form method="post">
				<p>Are you sure you want to take leave ?</p>
					{% csrf_token %}
					<a class="btn btn-warning" href="{% url 'demo:table' %}">Cancel</a>
	
					<input class="btn btn-danger" type="submit" href="{% url 'demo:table' %}" name= "Confirm" />
				</form>
			</div>
		</div>
	</div>
</body>
</html>

demo/templates/demo/table.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
  <link rel="stylesheet"  href="{%  static  'css/ta.css'  %}">
    <title>Document</title>
    
</head>
<body>
  {% block content%}
  <div style="background-color: rgb(127, 172, 255);"> <img src="{% static 'C:\enviroment\h\demo\image\logo.svg' %}"></div>
  <div id="mm"><table style="text-align: center" class="gridtable">
        <tr>
          <th style="width: 100px">Name</th>
          <th style="width: 100px">DOB</th>
          <th style="width: 100px">Date of joining</th>
          <th style="width: 100px"> Department</th>
          <th style="width: 100px">Designation</th>
          <th style="width: 100px">City</th>
          <th style="width: 100px">Country</th>
          <th style="width: 100px">No. of leaves</th>
          <th style="width: 100px">Leave</th>
          <th style="width: 100px">Update</th>
          <th style="width: 100px">Delete</th>

        </tr>
      
        {% for i in k %}
        <tr>
          
          <td>{{i.name}}</td>
          <td>{{i.DOB}}</td>
          <td>{{i.DOJ}}</td>
          <td>{{i.Department}}</td>
          <td>{{i.post}}</td>
          <td>{{i.City}}</td>
          <td>{{i.Country}}</td>
          <td>{{i.blog_views}}</td>
         
          <td> 
          {% if i.my_field == True %}
            <a href="{% url 'demo:leave' i.id %}" style="background-color:rgb(207, 247, 226)" >Working</a>
        
            {% else %}
            <a href="{% url 'demo:leave' i.id %}" style="background-color:rgb(207, 247, 226)" >Leave</a>{% endif %}
         </td>
          <td><a href="{% url 'demo:updateOrder' i.id %}" style="background-color:rgb(244, 254, 172)">Edit</a></td>
         
          <td><a href="{% url 'demo:delete_order' i.id %}" style="background-color:rgb(252, 226, 219)">Delete</a></td>
        </tr>
        
        {% endfor %}
      </table></div>
      {% endblock %}
</body>
</html>

demo/templates/demo/up.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"  href="{%  static  'css/new.css'  %}">
    <title>Document</title>
</head>

<body>
    
    <div style="background-color: rgb(127, 172, 255);"> <img src="{% static 'C:\enviroment\h\demo\image\logo.svg' %}"></div>
    <div id="mm"><table style="text-align: center",class="gridtable">
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input  type="submit" value="Submit" />
    </form>
</body>

</html>